import JSZip from "jszip";
import type { GeneratedFile } from "@/types/schema";

/**
 * Builds a ZIP buffer from a list of generated files.
 * Returns a Buffer ready to be sent as a binary HTTP response.
 */
export async function buildZip(files: GeneratedFile[]): Promise<Buffer> {
  const zip = new JSZip();

  for (const file of files) {
    // Group by target folder
    const folder =
      file.target === "prisma"
        ? "prisma"
        : file.target === "flutter"
          ? "flutter"
          : "typescript";

    zip.folder(folder)?.file(file.filename, file.content);
  }

  // Add a README inside the ZIP
  zip.file(
    "README.md",
    `# Generated by PolyCode AI\n\nGenerated on: ${new Date().toLocaleString()}\n\n## Files\n${files.map((f) => `- ${f.target}/${f.filename}`).join("\n")}\n`
  );

  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return buffer;
}
