import type { ParsedTable, GeneratedFile, GenerationTarget } from "@/types/schema";
import {
  toPrismaType,
  toDartType,
  toTypeScriptType,
  toPascalCase,
  toCamelCase,
} from "@/lib/mapTypes";

// ─── Prisma Schema Generator ─────────────────────────────────────────────────
export function generatePrisma(tables: ParsedTable[]): GeneratedFile {
  const lines: string[] = [
    `// Generated by PolyCode AI`,
    `// ${new Date().toISOString()}`,
    ``,
    `datasource db {`,
    `  provider = "postgresql"`,
    `  url      = env("DATABASE_URL")`,
    `}`,
    ``,
    `generator client {`,
    `  provider = "prisma-client-js"`,
    `}`,
    ``,
  ];

  for (const table of tables) {
    const modelName = toPascalCase(table.name);
    lines.push(`model ${modelName} {`);

    for (const col of table.columns) {
      const prismaType = toPrismaType(col.type);
      const nullable = col.nullable && !col.isPrimary ? "?" : "";
      const annotations: string[] = [];

      if (col.isPrimary) annotations.push("@id");
      if (col.isUnique && !col.isPrimary) annotations.push("@unique");

      // Auto-detect default for primary key
      if (col.isPrimary) {
        const isInt =
          col.type.toUpperCase().includes("INT") ||
          col.type.toUpperCase().includes("SERIAL");
        annotations.push(isInt ? "@default(autoincrement())" : "@default(cuid())");
      } else if (col.defaultValue) {
        if (
          col.defaultValue.toLowerCase() === "current_timestamp" ||
          col.defaultValue.toLowerCase() === "now()"
        ) {
          annotations.push("@default(now())");
        } else if (!isNaN(Number(col.defaultValue))) {
          annotations.push(`@default(${col.defaultValue})`);
        } else if (
          col.defaultValue.toLowerCase() === "true" ||
          col.defaultValue.toLowerCase() === "false"
        ) {
          annotations.push(`@default(${col.defaultValue.toLowerCase()})`);
        }
      }

      // Map db name if camelCase differs
      const fieldName = toCamelCase(col.name);
      const dbName =
        fieldName !== col.name ? `  @map("${col.name}")` : "";

      const annotationStr =
        annotations.length > 0 ? " " + annotations.join(" ") : "";
      lines.push(
        `  ${fieldName.padEnd(20)} ${(prismaType + nullable).padEnd(12)}${annotationStr}${dbName}`
      );
    }

    // Add relations
    for (const rel of table.relations) {
      if (rel.fromTable === table.name) {
        const relModel = toPascalCase(rel.toTable);
        const fieldName = toCamelCase(rel.toTable);
        lines.push(
          `  ${fieldName.padEnd(20)} ${relModel.padEnd(12)} @relation(fields: [${toCamelCase(rel.fromColumn)}], references: [${toCamelCase(rel.toColumn)}])`
        );
      }
    }

    // Add reverse relations (other tables pointing to this)
    for (const otherTable of tables) {
      for (const rel of otherTable.relations) {
        if (rel.toTable === table.name) {
          const relModel = toPascalCase(otherTable.name);
          const fieldName = toCamelCase(otherTable.name) + "s";
          lines.push(`  ${fieldName.padEnd(20)} ${relModel}[]`);
        }
      }
    }

    lines.push(`}`);
    lines.push(``);
  }

  return {
    filename: "schema.prisma",
    content: lines.join("\n"),
    target: "prisma",
  };
}

// ─── Flutter / Dart Generator ────────────────────────────────────────────────
export function generateDart(tables: ParsedTable[]): GeneratedFile[] {
  return tables.map((table) => {
    const className = toPascalCase(table.name);
    const lines: string[] = [
      `// Generated by PolyCode AI`,
      `// ${new Date().toISOString()}`,
      ``,
      `class ${className} {`,
    ];

    // Fields
    for (const col of table.columns) {
      const dartType = toDartType(col.type, col.nullable && !col.isPrimary);
      const fieldName = toCamelCase(col.name);
      lines.push(`  final ${dartType} ${fieldName};`);
    }

    lines.push(``);

    // Constructor
    const constructorParams = table.columns
      .map((col) => {
        const fieldName = toCamelCase(col.name);
        const isRequired = !col.nullable || col.isPrimary;
        return isRequired ? `required this.${fieldName}` : `this.${fieldName}`;
      })
      .join(", ");
    lines.push(`  ${className}({${constructorParams}});`);
    lines.push(``);

    // fromJson factory
    lines.push(`  factory ${className}.fromJson(Map<String, dynamic> json) {`);
    lines.push(`    return ${className}(`);
    for (const col of table.columns) {
      const fieldName = toCamelCase(col.name);
      const dartType = toDartType(col.type, false).replace("?", "");
      let cast = `json['${col.name}']`;

      if (dartType === "DateTime") {
        cast = `DateTime.parse(json['${col.name}'] as String)`;
      } else if (dartType === "int") {
        cast = `(json['${col.name}'] as num).toInt()`;
      } else if (dartType === "double") {
        cast = `(json['${col.name}'] as num).toDouble()`;
      } else if (dartType === "bool") {
        cast = `json['${col.name}'] as bool`;
      } else {
        cast = `json['${col.name}'] as ${dartType}${col.nullable && !col.isPrimary ? "?" : ""}`;
      }

      lines.push(`      ${fieldName}: ${cast},`);
    }
    lines.push(`    );`);
    lines.push(`  }`);
    lines.push(``);

    // toJson method
    lines.push(`  Map<String, dynamic> toJson() {`);
    lines.push(`    return {`);
    for (const col of table.columns) {
      const fieldName = toCamelCase(col.name);
      const dartType = toDartType(col.type, false).replace("?", "");
      if (dartType === "DateTime") {
        lines.push(`      '${col.name}': ${fieldName}.toIso8601String(),`);
      } else {
        lines.push(`      '${col.name}': ${fieldName},`);
      }
    }
    lines.push(`    };`);
    lines.push(`  }`);
    lines.push(`}`);

    return {
      filename: `${table.name.toLowerCase()}_model.dart`,
      content: lines.join("\n"),
      target: "flutter" as GenerationTarget,
    };
  });
}

// ─── TypeScript Interface Generator ─────────────────────────────────────────
export function generateTypeScript(tables: ParsedTable[]): GeneratedFile {
  const lines: string[] = [
    `// Generated by PolyCode AI`,
    `// ${new Date().toISOString()}`,
    ``,
  ];

  for (const table of tables) {
    const interfaceName = toPascalCase(table.name);
    lines.push(`export interface ${interfaceName} {`);

    for (const col of table.columns) {
      const tsType = toTypeScriptType(col.type);
      const fieldName = toCamelCase(col.name);
      const nullable = col.nullable && !col.isPrimary ? "?" : "";
      lines.push(`  ${fieldName}${nullable}: ${tsType};`);
    }

    lines.push(`}`);
    lines.push(``);

    // Also generate a Create DTO (without id/timestamps)
    const createFields = table.columns.filter(
      (c) =>
        !c.isPrimary &&
        !["created_at", "createdAt", "updated_at", "updatedAt"].includes(c.name)
    );

    if (createFields.length > 0) {
      lines.push(`export interface Create${interfaceName}Dto {`);
      for (const col of createFields) {
        const tsType = toTypeScriptType(col.type);
        const fieldName = toCamelCase(col.name);
        const nullable = col.nullable ? "?" : "";
        lines.push(`  ${fieldName}${nullable}: ${tsType};`);
      }
      lines.push(`}`);
      lines.push(``);
    }
  }

  return {
    filename: "types.ts",
    content: lines.join("\n"),
    target: "typescript",
  };
}
